spring:
  datasource:
    url: jdbc:h2:file:./Server/data/loading;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: neutron
    password:
    driverClassName: org.h2.Driver
    generate-unique-name: false
    name: loading
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect